### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by ScourgeRaven** [Project-IS12/IS12-Warfare#101]
If i try to Compile it i get a list of Errors and warnings. I don't know if i'm doing something wrong or missing. Thats why i share it with you because i can't find the problem.

loading IS12Warfare.dme
loading interface/skin.dmf
code\modules\admin\verbs\mapping.dm:44:warning (no_parent): ..: ..() has no parent proc to call
code\modules\mob\living\bot\mulebot.dm:222:warning (no_parent): ..: ..() has no parent proc to call
code\modules\mob\living\carbon\human\life.dm:1006:warning (no_parent): ..: ..() has no parent proc to call
code\modules\mob\living\simple_animal\hostile\retaliate\retaliate.dm:29:warning (no_parent): ..: ..() has no parent proc to call
code\modules\atmospherics\mainspipe.dm:75:warning (no_parent): ..: ..() has no parent proc to call
code\modules\overmap\ships\computers\helm.dm:32:warning (no_parent): ..: ..() has no parent proc to call
code\game\machinery\telecomms\telecomunications.dm:106:warning (no_parent): ..: ..() has no parent proc to call
code\modules\detectivework\microscope\microscope.dm:90:warning (no_parent): ..: ..() has no parent proc to call
code\modules\power\cable.dm:589:warning (no_parent): ..: ..() has no parent proc to call
code\modules\economy\EFTPOS.dm:272:warning (no_parent): ..: ..() has no parent proc to call
code\modules\projectiles\guns\projectile\mattguns.dm:375:error: 'sound/weapons/mg_deploy.ogg': cannot find file
code\game\gamemodes\warfare\barricade.dm:159:warning (no_parent): ..: ..() has no parent proc to call
code\game\objects\structures\bedsheet_bin.dm:124:error: : expected a constant number
code\game\turfs\simulated\wall_attacks.dm:75:warning (no_parent): ..: ..() has no parent proc to call
code\modules\mob\living\carbon\carbon.dm:119:error: to: range in switch must be from low to high number
code\controllers\subsystems\jobs.dm:217:error: job.minimum_character_age: expected a constant number
code\controllers\subsystems\jobs.dm:217:error: : expected a constant number
code\controllers\subsystems\jobs.dm:219:error: : expected a constant number
code\controllers\subsystems\jobs.dm:219:error: : expected a constant number
code\controllers\subsystems\jobs.dm:221:error: : expected a constant number
code\controllers\subsystems\jobs.dm:221:error: : expected a constant number
code\controllers\subsystems\jobs.dm:223:error: : expected a constant number
code\controllers\subsystems\jobs.dm:223:error: : expected a constant number
code\controllers\subsystems\jobs.dm:225:error: : expected a constant number
code\modules\organs\internal\lungs.dm:294:error: species.heat_level_1: expected a constant number
code\modules\organs\internal\lungs.dm:294:error: species.heat_level_2: expected a constant number
code\modules\organs\internal\lungs.dm:296:error: species.heat_level_2: expected a constant number
code\modules\organs\internal\lungs.dm:296:error: species.heat_level_3: expected a constant number
code\modules\mob\living\silicon\robot\life.dm:196:error: config.health_threshold_dead: expected a constant number
IS12Warfare.dmb - 17 errors, 12 warnings (7/16/24 7:04 pm)

**Comment by NotSoWizard** [comment]
[It wasn't updated to 515.1641](https://github.com/Project-IS12/IS12-Warfare/issues/100)

**Comment by NotSoWizard** [comment]
Simply, this build wasn't updated to 515.

**Comment by ScourgeRaven** [comment]
Ah okay, good to know.
Thanks for the help, now i have only one error

code\modules\projectiles\guns\projectile\mattguns.dm:375:error: 'sound/weapons/mg_deploy.ogg': cannot find file

**Comment by NotSoWizard** [comment]
> code\modules\projectiles\guns\projectile\mattguns.dm:375:error: 'sound/weapons/mg_deploy.ogg': cannot find file

Add [this](https://github.com/Project-IS12/IS12-Warfare/blob/bd56f766c401a90b5166a5203bae1d5189eb0a87/sound/weapons/mg_deploy.ogg) file to the path of "sound/weapons", and don't forget to rename it to "mg_deploy.ogg"

**Comment by ScourgeRaven** [comment]
Okay thanks for the help ^^
