### ISSUE TITLE
Medical Scanner Prints Ambiguous Name of Patient

### ISSUE THREAD

**Issue by Trexdude** [Project-IS12/IS12-Warfare#14]
If a patient's face is obscured and their name is ambiguous, the medical scanner will print that ambiguous name instead of their actual name. May be a feature.

To reproduce:
1) Scan a human who's actual name is not visible to you with a handheld medical scanner.
2) Read the "Scan results for" output in the chat.

May also be present in other cases where the person's actual name is displayed/written.

**Comment by mattmatterson111** [comment]
Looking into it.

**Comment by mattmatterson111** [comment]
Not an issue.
