### ISSUE TITLE
Surgery Skill Does not Apply, possibly only for Practitioners, not sure if Bug

### ISSUE THREAD

**Issue by Trexdude** [Project-IS12/IS12-Warfare#18]
During the round today while playing (Red) Practitioner with a surgery skill of "versed" multiple surgery steps failed, around the ratio of maybe one out of seven.
The next round while playing Practitioner with a surgery skilled of "expert", a similar ratio (presumably one to seven) of surgery steps failed happened too.
Ain't sure if a recent update's bugged the skills for practitioners, possibly not a bug.

To recreate:
1) Join as practitioner, presumably on either team.
2) Attempt to do surgery on someone, optionally count the number of steps failed to steps succeeded.

**Comment by mattmatterson111** [comment]
Not a bug with skills.
