### ISSUE TITLE
unloading a revolver drops 8 rounds instead of 6

### ISSUE THREAD

**Issue by AndroBetel** [Project-IS12/IS12-Warfare#19]
when you unload a practitioneer's revolver the log is You unload 6 rounds from Captain's Special. but it drops 8 rounds in two stacks. you can't load last two rounds back.

**Comment by mattmatterson111** [comment]
Bizarre. I'll look into it.

**Comment by mattmatterson111** [comment]
Bug does not appear for Sniper revolver. Looking into prac now.

**Comment by Trexdude** [comment]
Saw this too when I've been playing far as I know.

**Comment by mattmatterson111** [comment]
https://github.com/Project-IS12/IS12-Warfare/commit/20107fc6224fbbb494b125a6f531b410c447fc54 Gave the practitioners normal revovlers. Will continue to monitor this issue.

**Comment by mattmatterson111** [comment]
Fixed.
