### ISSUE TITLE
Medbay Symbol is Hidden Behind Wall Sprite in Trench Medbays

### ISSUE THREAD

**Issue by Trexdude** [Project-IS12/IS12-Warfare#26]
Look at the trench medbay walls, there's a medbay sign hidden behind them near the curtains.

**Comment by mattmatterson111** [comment]
This is due to signs being on a lower plane than walls. Should be a one line fix.

**Comment by glyphloom** [comment]
Fixed it on my map a while ago. Change plane from -15 to -6 (To follow posters standart)

**Comment by glyphloom** [comment]
#34

**Comment by mattmatterson111** [comment]
Fixed in #34
