### ISSUE TITLE
Level-z bug with torch fixtures.

### ISSUE THREAD

**Issue by glyphloom** [Project-IS12/IS12-Warfare#39]
If you have torch fixtures and there is an open underneath them, when you take this torch, it will also spawn the torch on the level underneath as illustrated. 
![image](https://user-images.githubusercontent.com/49097167/95291575-ff3ae380-0899-11eb-9dd3-40a1a1f91055.png)
![image](https://user-images.githubusercontent.com/49097167/95291616-17126780-089a-11eb-95bf-0252f7efc424.png)

**Comment by duke-1** [comment]
Where did you get this to happen? Could not recreate locally.

**Comment by mattmatterson111** [comment]
Map specific issue. Map is not actively used. Closing.

**Comment by glyphloom** [comment]
I'm not sure if it was map specific. Seem like a general thing to occure - watch out for torch placements that are reachable above open spaces in the future. 

There is no case like that on Oldfare or Astrafare - i made sure that's not possible for this bug to occure on them, i guess.

**Comment by mattmatterson111** [comment]
I'll look into it again then. I can't seem to replicate it when testing locally though.

**Comment by glyphloom** [comment]
Maybe it has something to do with how the z-layers and service landmarks were setted up... I still have the source code with this unfinished map if you want to look at it.
