### ISSUE TITLE
Removing a dirt barricade while standing and on the same tile keeps your sprite raised above the center of the tile after moving

### ISSUE THREAD

**Issue by Trexdude** [Project-IS12/IS12-Warfare#68]
I think that removing a dirt barricade while yer standing on the barricade causes your sprite to remain shifted from the center of the tile even after you move off of the tile the dirt barricade was on. I've seen it happen a couple of times and I think it's caused by removing a barricade while standing on it, though it may be caused by other things. I think you can patch this issue currently by lying down, which causes yer sprite to shift back when standing up again.

**Comment by mattmatterson111** [comment]
:mistake:
