### ISSUE TITLE
AGPL license violation

### ISSUE THREAD

**Issue by ike709** [Project-IS12/IS12-Warfare#71]
![image](https://user-images.githubusercontent.com/5714543/126232187-0c6d4cdf-2241-489b-9c72-8fbd8289cc34.png)
![image](https://user-images.githubusercontent.com/5714543/126232200-10da0822-115a-46a8-8f5d-0c80446670cd.png)

This is not how the AGPL works. You can't mix AGPL and GPL like this, any GPL code combined with AGPL code falls under the AGPL, though the original separate GPL code can remain GPL.

This is covered in section 13, paragraph 2 of the AGPLv3: https://www.gnu.org/licenses/agpl-3.0.en.html
The "secret module" must be provided under the terms of the AGPL if it has ever been compiled as part of this project and hosted.

**Comment by Iamgoofball** [comment]
Mhm. Due to the way BYOND works, when your GPL code is compiled into the .dmb alongside the AGPL code, your GPL code is now AGPL and therefore to actually comply with the AGPL, you need to provide that newly-AGPL code to any user who connects to your server and requests it.

**Comment by Iamgoofball** [comment]
After inquiring in discord apparently @MrStonedOne consulted with them about this and gave them the all clear? I'm interested to hear what's going on with this.
![Discord_UcKIDK3Zy6](https://user-images.githubusercontent.com/4081722/126233962-832b8de9-a32f-4f56-9e4f-bf341a0554e9.png)

**Comment by LemonInTheDark** [comment]
MSO's opinion only matters insofar as his code is used here. Mixing secret and agpl code is a license violation no matter how you slice it, since that's kinda the point of agpl

**Comment by mattmatterson111** [comment]
Not a code quality issue. Steps will be taken to resolve any legal issues but I do not want my open issues clogged with stuff that isn't glitches.
