### ISSUE TITLE
Equipping outer armour (O_CLOTHING) on the appropriate slot makes it uninteractable

### ISSUE THREAD

**Issue by Lambda-Epsilon** [Project-IS12/IS12-Warfare#73]
Seems to plague all /armor types.

Upon equipping it, highlighting over it on the HUD will not display its name, rather that of the tile behind the HUD. It cannot be taken off from this slot, and seems to as well prevent I_CLOTHING slotted clothing from being equipped.

This is occurring on my own fork of the repo, however nothing relating to clothing has been modified in any way.

**Comment by glyphloom** [comment]
Non-reproducible. It works fine.

**Comment by mattmatterson111** [comment]
Never been able to reproduce it either. I think it's safe to close this for now.
